project:
  type: site
  output-dir: docs
site:
  title: "日常记录"
  site-url: https://ruiqiangjiao.github.io/daily-recode/
  repo-url: https://github.com/ruiqiangJiao/daily-recode/
  repo-actions: [edit]
  page-navigation: true
  
  navbar:
    type: dark
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "主页"
      - about.qmd
      - refrence.qmd
      - sidebar:programming
      - sidebar:algorithm
      
  sidebar:
    - id: programming
      title: "编程"
      style: "docked"
      background: light
      collapse-level: 2
      align: left
      contents:
        - section: "python"
          contents:
            - rmd/programming/python/read-redis-cluster.qmd
            - rmd/programming/python/read-mysql.qmd
            - rmd/programming/python/frequent-function.qmd
            - rmd/programming/python/pytorch.qmd
        - section: "R"
          contents:
            - rmd/programming/R/about.qmd
        - section: "git"
          contents:
          - rmd/programming/git/refrence.qmd
        - section: "spark"
          contents:
          - rmd/programming/spark/install.qmd
          - rmd/programming/spark/read-hbase.qmd
          - rmd/programming/spark/read-mysql.qmd
          - rmd/programming/spark/submit-run-task.qmd
        - section: "SQL"
          contents:
          - rmd/programming/SQL/MySQL.qmd
        - section: 'Leet code'
          contents:
          - rmd/programming/leetcode/refrence.qmd
        - section: '软件'
          contents:
          - rmd/programming/software/vim.qmd
          - rmd/programming/software/latex.qmd
         
    - id: algorithm
      title: "算法"
      contents:
        - section: "统计学"
          contents:
            - rmd/algorithm/statistics/elements_of_statistical_learning.qmd
            - rmd/algorithm/statistics/isolation_forest.qmd
            - rmd/algorithm/statistics/lof.qmd
            - rmd/algorithm/statistics/XGboost.qmd
        - section: "强化学习"
          contents:
            - rmd/algorithm/reinforcement_learning/about.qmd
        - section: "深度学习"
          contents:
            - rmd/algorithm/deep_learning/dive_into_deep_learning.qmd
        - section: "其它"
          contents:
            - rmd/algorithm/deep_learning/slam.qmd
            - rmd/algorithm/deep_learning/geohash.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

