---
title: "Vim"
jupyter: python3
---

## 常用命令

- 删除
  
    - dd:删除游标所在的一整行(常用)；
    
    - ndd:n为数字。删除光标所在的向下n行，例如20dd则是删除光标所在的向下20行；
    
    - d1G:删除光标所在到第一行的所有数据；
    
    - dG:删除光标所在到最后一行的所有数据；
    
    - d$:删除光标所在处，到该行的最后一个字符；

    - d0:那个是数字0,删除光标所在到该行的最前面的一个字符；

    - x,X:x向后删除一个字符(相当于[del]按键),X向前删除一个字符(相当于[backspace]即退格键)；
    
    - nx:n为数字，连续向后删除n个字符；
    
    - dw: 删除自当前光标至下一个word的开头；
    
    - db: 删除自当前光标至前一个word的开始；
    
    - diw: 删除当前光标所在的word(不包括空白字符)；
    
    - daw: 删除当前光标所在的word(包括空白字符)
    
- 复制

    - yy: 复制游标所在的那一行(常用)；
    
    - nyy: n为数字。复制光标所在的向下 n 行；
    
    - y1G: 复制游标所在行到第一行的所有数据；
    
    - yG: 复制游标所在行到最后一行的所有数据；
    
    - y0: 复制光标所在的那个字符到该行行首的所有数据；
    
    - y$: 复制光标所在的那个字符到该行行尾的所有数据；
    
- 粘贴

    - p: 将已复制的数据在光标下一行贴上;
    
    - P: 已复制的数据在光标贴在游标上一行；
    
- 搜索

    - /word	向光标之下寻找一个名称为 word 的字符串；
    
    - ?word	向光标之上寻找一个字符串名称为 word 的字符串；
    
    - n	这个 n 是英文按键。代表重复前一个搜寻的动作；
    
    - N	这个 N 是英文按键。与 n 刚好相反，为『反向』进行前一个搜寻动作；
    
- 光标
  
    - w 光标移动至下一个单词的开头
    
    - W 光标移动至下一个长单词的开头
    
    - b 光标移动至上一个单词的开头
    
    - B 光标移动至上一个长单词的开头
    
    - e 光标移动至下个字的字尾
    
    - E 光标移动至下个长字的字尾
    
    - ge 前一个单词的最后一个字符
    
- 编辑模式

    - i 当前光标前插入
    
    - I 光标所在行首插入
    
    - o 当前行下插入空行
    
    - O 当前行上插入空行
    
    - a 当前光标后插入
    
    - A 光标所在行末插入
    
    - ddp/P 光标所在的上下行互换位置
    
- 改变文本

    - cc/S: 改变整行,但是保持原来的缩进；
    
    - c$/C: 改变当前光标到行尾的内容；
    
    - ciw : 改变当前光标所在的word(不包括空白字符)；
    
    - caw : 删除当前光标所在的word(包括空白字符)
    
- 折叠

    - z + c : 折叠
    - z + o : 拆开
    - z + M : 折叠所有代码块
    - z + R : 拆开所有代码块


## 参考

[VIM 中文帮助手册](http://vimcdoc.sourceforge.net/doc/usr_toc.html)

[Learning Vim](https://github.com/dofy/learn-vim)
